### ISSUE TITLE
Question: How do you resize/color the icons when using with jQueryUI Button Widget?

### ISSUE THREAD

**Issue by toferj** [mkkeck/jquery-ui-icons#12]
I often have markup like this:
`<button class="dateButton small-button">Select Date</button>`

and corresponding JS like this:
```
    local.btns.jDateButtons = $('.dateButton');

    ...

    local.btns.jDateButtons.button({
        text: false,
        icons:{
            primary: 'ui-icon-calendar'
        }
    }).off().on('click',function(){
        ...
    });
```
I think I must be missing something here. The markup that contains the `... ui-icon ui-icon-calendar ...` isn't created until later and it's done by the jQuery UI button widget. So, where exactly do I put the information for the size and color of the icons?

Am I meant to add CSS like this: ??
```
    .ui-icon.ui-icon-calendar{
        font-size: 135%;
        color: #00FF00;
    }
```
How else can I target the span tag that the button widget creates for me on the fly which is where the font-size and color directives apparently need to go?

The above CSS would appear to work, but what if I have multiples of the same icons on the page and I want them to be different sizes or different colors?

**Comment by mkkeck** [comment]
You have to put for different sizes/colors into different classes:
```css
.blue .ui-icon {
 color: #0f0;
}
.large .ui-icon {
  font-size: 4em;
}
```
In HTML you can use:
```html
<span class="blue"><span class="ui-icon ui-icon-calendar"></span></span>
<span class="blue large"><span class="ui-icon ui-icon-calendar"></span></span>
<span class="large"><span class="ui-icon ui-icon-calendar"></span></span>
```

**Comment by toferj** [comment]
My point was that the markup is generated on the fly, by jQuery UI. I don't
create anything more than a button tag. The corresponding spans get
generated at runtime by jQuery when calling `.button()`. So the solution
doesn't work well for me there. :(

**Comment by mkkeck** [comment]
Okay, then please try follow CSS:
```css
.ui-button.dateButton .ui-icon {
  color: #0f0;
  font-size: 4em;
}
.ui-button.dateButton .ui-icon:after {
 /* Perhabs edit this too (position, size ...)
    font-size: inherit; 
 */
}
````
in HTML:
```html
<button class="dateButton small-button">Select Date</button>
```
jQuery should not replace/remove the CSS class(es) `dateButton` of your button. If so, then add a extra class (e.g. `your-class`) for your button or put your button into a `<span>` with your special class/styles.
Example:
```css
/* CSS */
.your-class > button .ui-icon {
  color: #0f0;
  font-size: 4em;
}
.your-class > button .ui-icon:after {
 /* Perhabs edit this too (position, size ...)
    font-size: inherit; 
 */
}
```
```html
<!-- HTML -->
<span class="your-class"><button class="dateButton small-button">Select Date</button></span>
```

> How else can I target the span tag that the button widget creates for me on the fly

Please check the Button-Widget Api on jQuery UI: http://api.jqueryui.com/button/
